### ISSUE TITLE
No pytorch cuda

### ISSUE THREAD

**Issue by kbrodt** [drivendataorg/floodwater-runtime#3]
Hi, I'm trying to upload a submission to the [competition](https://www.drivendata.org/competitions/81/detect-flood-water/page/385/) and get the following error

```
...
torch.cuda.is_available() is False. If you are running on a CPU-only machine,
please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
...
```

Seems pytorch is installed without cuda support.

**Comment by aelbakry** [comment]
Same here...

**Comment by isms** [comment]
Working on this issue - thanks for flagging. Seems to be a version mismatch. Should be fixed shortly.

**Comment by isms** [comment]
Should be fixed, it was indeed some kind of CUDA version mismatch with the host. Try now.
